from django.core.exceptions import ObjectDoesNotExist


if __name__ == '__main__':
    pass
